// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdHglXrefa1i2CcZ53gRXwEtgGaQkLAt0',
    appId: '1:833880845282:web:e36580235f5d0a295da7bb',
    messagingSenderId: '833880845282',
    projectId: 'fir-project-3b9e0',
    authDomain: 'fir-project-3b9e0.firebaseapp.com',
    storageBucket: 'fir-project-3b9e0.firebasestorage.app',
    measurementId: 'G-XYZ1J9C69R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCo7UUKfehZbgHbVaMYZ0IDKeeXoSs_Zw',
    appId: '1:833880845282:android:335f21352e75dddb5da7bb',
    messagingSenderId: '833880845282',
    projectId: 'fir-project-3b9e0',
    storageBucket: 'fir-project-3b9e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC75iBXAWPW7J9AB7qwV44M6V_O3_awVEM',
    appId: '1:833880845282:ios:259148f485be10cc5da7bb',
    messagingSenderId: '833880845282',
    projectId: 'fir-project-3b9e0',
    storageBucket: 'fir-project-3b9e0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC75iBXAWPW7J9AB7qwV44M6V_O3_awVEM',
    appId: '1:833880845282:ios:259148f485be10cc5da7bb',
    messagingSenderId: '833880845282',
    projectId: 'fir-project-3b9e0',
    storageBucket: 'fir-project-3b9e0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdHglXrefa1i2CcZ53gRXwEtgGaQkLAt0',
    appId: '1:833880845282:web:45b6d12c3d58fb955da7bb',
    messagingSenderId: '833880845282',
    projectId: 'fir-project-3b9e0',
    authDomain: 'fir-project-3b9e0.firebaseapp.com',
    storageBucket: 'fir-project-3b9e0.firebasestorage.app',
    measurementId: 'G-9DT7LC7QZS',
  );
}
